PATCH_SIZE = 9

NUM_IMAGES = 200
NUM_TRAIN_IMAGES = 180

MAX_DISPARITY = 100

# PUTANJE
__PROJECT_PATH = 'D:/ZAVRSNI/Zavrsni-rad/'
DISPARITY_DATA_PATH = __PROJECT_PATH + 'disparity_data.npy'

__IMAGES_ROOT_PATH = __PROJECT_PATH + 'Kitti/stereo/'
DISPARITY_IMAGE_ROOT_PATH = __IMAGES_ROOT_PATH + 'disp_noc_0/'
LEFT_IMAGE_ROOT_PATH = __IMAGES_ROOT_PATH + 'image_2/'
RIGHT_IMAGE_ROOT_PATH = __IMAGES_ROOT_PATH + 'image_3/'

TRAINED_MODEL_PATH = __PROJECT_PATH + 'trained_model.pth'

