PATCH_SIZE = 9
MAX_DISPARITY = 100

NUM_IMAGES = 200
NUM_TRAIN_IMAGES = 160
TRAIN_IMAGES_START_INDEX = 0
TRAIN_IMAGES_END_INDEX = NUM_TRAIN_IMAGES
VALIDATION_IMAGES_START_INDEX = NUM_TRAIN_IMAGES
VALIDATION_IMAGES_END_INDEX = NUM_IMAGES

# PUTANJE
__PROJECT_PATH = 'D:/ZAVRSNI/Zavrsni-rad/'

__DISPARITY_DATA_ROOT_PATH = __PROJECT_PATH + 'disparity_data/'
TRAIN_DISPARITY_DATA_PATH = __DISPARITY_DATA_ROOT_PATH + 'train_disparity_data.npy'
VALIDATION_DISPARITY_DATA_PATH = __DISPARITY_DATA_ROOT_PATH + 'validation_disparity_data.npy'

__IMAGES_ROOT_PATH = __PROJECT_PATH + 'Kitti/stereo/'
DISPARITY_IMAGE_ROOT_PATH = __IMAGES_ROOT_PATH + 'disp_noc_0/'

NORMALIZED_IMAGES_PATH = __IMAGES_ROOT_PATH + 'normalized/'
NOT_NORMALIZED_IMAGES_PATH = __IMAGES_ROOT_PATH + 'not_normalized/'
__LEFT_IMAGE_FOLDER = 'image_2/'
__RIGHT_IMAGE_FOLDER = 'image_3/'

NORMALIZED_LEFT_IMAGE_ROOT_PATH = NORMALIZED_IMAGES_PATH + __LEFT_IMAGE_FOLDER
NORMALIZED_RIGHT_IMAGE_ROOT_PATH = NORMALIZED_IMAGES_PATH + __RIGHT_IMAGE_FOLDER
NOT_NORMALIZED_LEFT_IMAGE_ROOT_PATH = NOT_NORMALIZED_IMAGES_PATH + __LEFT_IMAGE_FOLDER
NOT_NORMALIZED_RIGHT_IMAGE_ROOT_PATH = NOT_NORMALIZED_IMAGES_PATH + __RIGHT_IMAGE_FOLDER

TRAINED_MODEL_PATH = __PROJECT_PATH + 'trained_model_13.pth'

